### PR TITLE
camweb: remove trailing slash from request for a file-backed page

### PR DESCRIPTION
**Pull request by dlipovetsky**
This PR is one way of addressing #967.

A request for `/community/` or `/doc/overview/` redirects to `/community` and `/doc/overview`, respectively. Prior to this change, an error page was served.

### CODE REVIEW

**Comment by mpl** [comment]
Thanks, but we do not take PR. We used to be able to import them with gerrithub, but it's broken atm.

Please let me know if you want to contribute with gerrit (https://camlistore.org/code#contributing), of if you'd prefer that I do it myself (while crediting you as the author).

**Comment by dlipovetsky** [comment]
My mistake! I thought that gerrit might be for maintainers only. I'll follow the instructions, then submit my changes on gerrit. Thanks.

**Comment by mpl** [comment]
don't close the issue until a fix has actually been merged in the repo :-)

**Comment by mpl** [comment]
oops, my bad, I confused this page with the issue page. nvm.

**Pull request closed without merging**
