### PR TITLE
Fix camget/cammount so they accept --help

### LINKED ISSUE #671: camget and cammount ignore -help flag
`camget` and `camget -help` don't print help. `camget -foo` prints help.

### PR DESCRIPTION
**Pull request by amnk**
Fixes #671

### CODE REVIEW

**Comment by amnk** [comment]
cc @edrex

**Comment by amnk** [comment]
This is my first commit to camlistore - please let me know if I did something stupid :)

**Comment by edrex** [comment]
Hi @amnk, welcome! 

We actually don't use Github for code review. Please read https://camlistore.org/code#contributing, sign the contributor level agreement, and then you can submit your changes to the Gerrit review board with `devcam review`. Thanks!

**Comment by amnk** [comment]
@edrex resubmitted, thanks! So I can abandon this pull request and only use github for issues?

**Comment by mpl** [comment]
@amnk yes, you can abandon the PR.

**Pull request closed without merging**
